# Generated by Django 3.1.2 on 2020-10-17 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0002_customer_default_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Product Name')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Price')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_app.customer')),
            ],
        ),
    ]
